Repository vaibhavnirmal2001/DSA-hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#43 Sort By Set Bit Count
  Sort By Set Bit Count/README.md
  Sort By Set Bit Count/Sort By Set Bit Count.cpp
Labels: hacktoberfest-accepted

#44 226-Invert Tree
  226_invert Tree.cpp
  226_invert Tree/invert_tree.cpp
  226_invert Tree/notes.md
  226_invert Tree/readme.md
Labels: hacktoberfest-accepted

#45 Add "26. Remove Duplicates from Sorted Array"
  26. Remove Duplicates from Sorted Array/26. Remove Duplicates from Sorted Array.java
  26. Remove Duplicates from Sorted Array/Readme.md
Labels: hacktoberfest-accepted

#47 Leetcode Solution Of Merge Sorted Array.
  LeetCode Solution/Merge Sorted Array.cpp
  LeetCode Solutions/README.md
Labels: hacktoberfest-accepted

#48 Add "69. Sqrt(x)"
  69. Sqrt(x)/69. Sqrt(x).java
  69. Sqrt(x)/Readme.md
Labels: hacktoberfest-accepted

#53 Added linear and binary search codes in Java
  Binary search/BinarySearch.java
  Binary search/Ceiling.java
  Binary search/FirstAndLastPosition.java
  Linear search/EvenDigits.java
  Linear search/FindMin.java
  Linear search/Main.java
Labels: hacktoberfest-accepted

#59 Update README.md
  README.md
Labels: hacktoberfest-accepted

#61 Update README.md
  README.md
Labels: Hacktoberfest

#62 I have added a question with solution to find diameter of a binary tree
  diameter of binary tree/README
  diameter of binary tree/a.exe
  diameter of binary tree/diameter.cpp
Labels: Hacktoberfest

#105 added BinarySub CodeChef Long Challenge 2022
  BinarySub/BinarySubstitution.cpp
  BinarySub/Readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#79 Graph algos
  BFS.cpp
  DFS.cpp
  Disjisktra.cpp
  check_star_graph.cpp
  kruskals.cpp
Labels: Hacktoberfest

#91 Create Best Time to Buy and Sell Stock - 121-leetcode/
  Best Time to Buy and Sell Stock - 121-leetcode
Labels: Hacktoberfest

#111 N-Queen problem
  N-queen problem/N-queen problem.cpp
  N-queen problem/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#120 Added code for heap sort in java
  HeapSort.java
Labels: Hacktoberfest, hacktoberfest-accepted
